### ISSUE TITLE
Lambda Function Times Out When Invoked Within AWS

### ISSUE THREAD

**Issue by heretogo** [cloudreach/aws-lambda-es-cleanup#20]
When I run `es-cleanup.py` locally it deletes the indices as expected.

When I run 'Test' in Lambda or `lambda invoke` on the command-line I get a timeout and the operation doesn't complete. CloudWatch Logs simply shows the time the command was invoked but no errors.

What could be wrong here?

**Comment by giuliocalzo** [comment]
hi @heretogo which version are you using?
do you deploy with serverless or terraform?

can you attach the output of cloudwatch logs?

**Comment by heretogo** [comment]
My version of `es-cleanup.py` is the same as the one found in the Master branch of this repo. I am using Python2.7 and Elasticsearch 6.2.

I did not deploy with serverless or terraform. I followed the CLI/Lambda deploy instructions in the README. I did not use serverless or terraform.

The logs simply show:
```
START RequestId: 465a44d3-ce4b-11e8-9c4d-a9fcf2832d13 Version: $LATEST
END RequestId: 465a44d3-ce4b-11e8-9c4d-a9fcf2832d13
REPORT RequestId: 465a44d3-ce4b-11e8-9c4d-a9fcf2832d13	Duration: 180028.23 ms	Billed Duration: 180000 ms Memory Size: 128 MB	Max Memory Used: 26 MB	
2018-10-12T18:21:53.555Z 465a44d3-ce4b-11e8-9c4d-a9fcf2832d13 Task timed out after 180.03 seconds
```

**Comment by giuliocalzo** [comment]
Question @heretogo , which indexes are in your ES?
can you tell me how did you setup `index` and `index_format` env var?

**Comment by heretogo** [comment]
I left those blank assuming the script will use the default values ('all' and '%Y.%m.%d'). Like I mentioned, when I ran this from my workstation it deleted the correct indices.

In Elasticsearch the index names are like those below:
`prod-application-2018.09.13
staging-application-2018.09.13`

Do you think I need to add a `-` to the `index_format`?

**Comment by heretogo** [comment]
This works now.

Some information about my architecture. The Elasticsearch cluster lives in a private subnet. I had to give the AWSLambdaVPCAccessExecutionRole policy in order for the script to work.

Hopefully this is helpful to someone else. Perhaps you could document this in the `README.md` however it's really more on the AWS side.

**Comment by giuliocalzo** [comment]
if you don't overwrite using lambda env vars, is going to work.
the default values are `all` and `%Y.%m.%d` and this is going to match your indexes.

can i suggest to add at line 181 a `print` to see which index is going to be processed
```
print(index["index"])
```

**Comment by giuliocalzo** [comment]
ok I saw only now, I'm going to update the IAM role in case the lambda is using inside the VPC.

**Comment by heretogo** [comment]
:+1:
