### ISSUE TITLE
Delete by Mapping

### ISSUE THREAD

**Issue by piedmont01** [cloudreach/aws-lambda-es-cleanup#3]
Sorry, this is an enhancement! 

aws-lambda-es-cleanup works when the date is part of the index like cwl-2017.08.28. 

I'm wondering how challenging it would be to delete by date as part of a mapping? In the following example, the date is part of the index. 

```PUT my_index
{
  "mappings": {
    "my_type": {
      "properties": {
        "date": {
          "type":   "date",
          "format": "yyyy-MM-dd"
        }
      }
    }
  }
}

**Comment by giuliocalzolari** [comment]
Hi you can easily change the date format setting the OS variable `index_format`

in your case `index_format = "%Y-%m-%d"`

**Comment by giuliocalzo** [comment]
unfortunately this feature is not implemented because it will cover a very specific use cases.
The main purpose of this code is to easily cleanup a standard installation of AWS ES and add on every Elasticsearch API the header signature in order to control the access with AWS IAM.
