### ISSUE TITLE
skip_index parameter to support regular expressions

### ISSUE THREAD

**Issue by EduSandu** [cloudreach/aws-lambda-es-cleanup#31]
Taking the following scenario into discussion where we would have the ES cleaner run against all indices in an ES cluster with the exception of a particular indice pattern, for example to exclude all indices matching `openshift-infra-%Y.%m.%d`.

I've tested adding an expression as `openshift-infra-*` to the _skip_index_ parameter and when invoked manually, it finds the respective indice but also returns:
- "Keeping index: openshift-infra-2019.10.01"

For the default .kibana,.kibana_5 indice that "Keeping..." output is not returned, thus I assume it is skipped successfully.

Not very familiar with Python, thus I want to ask if the `skip_index` variable supports delimiting indices through regular expressions? Alternatively I guess the indices can be defined in the `index` variable instead of `all` value, which also raises the same question, if it supports expressions? :)

**Comment by giuliocalzo** [comment]
@EduSandu  that sounds like a great idea.
a similar issue was resolved in #26 would be awesome to have some help from the community to implements regular expression for the index to skip and the index to delete.

I will try a beta version in a dedicate branch

**Comment by giuliocalzo** [comment]
@EduSandu please check the new version 
https://github.com/cloudreach/aws-lambda-es-cleanup/blob/e0f600561e2f0914befb2f8c236658ff47cfe8f0/es-cleanup.py

and test it.

**Comment by EduSandu** [comment]
@giuliocalzolari awesome stuff - tested OK it matched and processed all indexes using the wildcard match and also skipped the _.kibana_ indexes.

I omitted initially during testing to change the `skip_index` param, which was using the comma-delimited values - the cleaner job deleted the `.kibana_N` indexes, but was able to restore them from a snapshot. 

Wondering if the `.split(",")` delimeter can be kept and used to separate multiple expressions in the _index_ & _skip_index_ variables?  
This gives more granular control and lets you to keep more important indices longer (have them skipped via the expression matching their pattern in skip_index) and drop the ones that are not that relevant earlier, in order to save disk usage.

**Comment by giuliocalzo** [comment]
@EduSandu  uhmm very wierd... 
I've setup the `skip_index` to also use the regexp
https://github.com/cloudreach/aws-lambda-es-cleanup/blob/e0f600561e2f0914befb2f8c236658ff47cfe8f0/es-cleanup.py#L56

are you using Terraform to deploy it? 
because I've realised the default value for terraform is still `".kibana"` and this pattern does not match `.kibana_N`

can you confirm it?

**Comment by EduSandu** [comment]
@giuliocalzolari no this wasn't a new domain standed up using Terraform.
`skip_index` works using the regexp method, only the initial test cleared the `.kibana_N` indices (skip_index was still using the prior comma delimited format) 

Would like to test having multiple expressions with a `,` delimeter, for the reasons mentioned above - guessing the following lines 
https://github.com/cloudreach/aws-lambda-es-cleanup/blob/e0f600561e2f0914befb2f8c236658ff47cfe8f0/es-cleanup.py#L55-L56
should be amended as such? Not sure if `re.search` will support it
`self.cfg["skip_index"] = self.get_parameter("skip_index", ".kibana*").split(",")`

**Comment by giuliocalzo** [comment]
The Regexp done like that
```
 self.cfg["skip_index"] = self.get_parameter("skip_index", ".kibana*") 
```
can match multiple patterns/indexes 
I will open a new PR with the current changes

@EduSandu thanks for your support!

**Comment by giuliocalzo** [comment]
#33
