### ISSUE TITLE
CFN

### ISSUE THREAD

**Issue by piedmont01** [cloudreach/aws-lambda-es-cleanup#4]
Thank you for your response regarding me earlier issue. I agree that my request was too customized to offer any benefit. 

If it's of interest, I built a CFN for this at, https://github.com/piedmont01/aws-lambda-es-cleanup/blob/master/CFN/aws-lambda-es-cleanup.yaml

Erick Kendall

**Comment by giuliocalzo** [comment]
very cool !
I like the CFN in YAML mode, the only issue is you still how to upload the lambda function code into S3, this is the main reason why we suggest serverless.com framework, let you upload a function and create the cloudformation all in one action, perfect to be added into a CI/CD pipeline.
